
logging:
  level:
    root: error
    java: ERROR
    com.lhm.mapper: trace
  file: /home/logs/log.log
## Server
server:
  port: 80
  tomcat:
    uriEncoding: UTF-8



spring:
  elasticsearch:
    jest:
      uris:
        - http://192.168.98.134:9200 #es服务器的地址
      read-timeout: 5000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wish_bottle?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver


      initial-size: 5
      max-active: 20
      min-idle: 5

      max-wait: 60000
      pool-prepared-statements: true

      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

      time-between-eviction-runs-millis: 60000

      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20

      use-global-data-source-stat: true
      filters: stat
      filter:

        stat:
          slow-sql-millis: 200
          log-slow-sql: true


      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*

        login-username: admin
        login-password: admin
        allow:
        deny:

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 100000 # 连接超时
    pool:
      maxIdle: 10   #最大空闲连接
      max-active: 8   # 最大连接数
      max-wait: -1  # 最大等待时间（使用负值表示没有限制）
      min-idle: 0   # 连接池最小空闲连接

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.lhm.star.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true



mapper:

  mappers: com.lhm.star.utils.common.MyMapper
  not-empty: false
  identity: MYSQL


pagehelper:
  helperDialect: mysql
  pagehelper: reasonable=true
  supportMethodsArguments: true
  params: count=countSql

